config/routes.rb
Rails.application.routes.draw do
  get 'places/index'
  get 'places/search'
  get 'places/search2'
  get 'places/new'
  
  
  post 'cooks/new'
      
  devise_for :users
  root to: "places#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :cooks do
    collection do
      get 'search'
    
      
      
    end
  

    resources :places, only: [:index,:new,:create]
    resources :cooks, only: [:index,:new,:create]
    
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ActiveStorage
  self.data = [
    {id: 1, name: '---' },     
    {id: 2, name: '沖縄'},
    {id: 3, name: '那覇市'},
    {id: 4, name: '浦添市'},
   
    
  ]
  include ActiveHash::Associations
  has_many :place

  
end

app/models/cook.rb
class Cook < ApplicationRecord
  has_one_attached :image
end

app/models/map.rb
class Map < ApplicationRecord
  after_validation :geocode

  private
  def geocode
    uri = uri.escape(http://maps.google.com/maps/api/geocode/json?address"+self.address.gsubkey=AIzaSyAc8ucfbF9aY5Jn9VehhJZ852fopENuQT)
    res = HTTP.get(uri).to_s
    response = json.parse(res)
    self.latitude = response["results"][0]["geometry"]["location"]["lat"]
    self.longitude = response["results"][0]["geometry"]["location"]["lng"]
  end
end

app/models/place.rb
class Place < ApplicationRecord
  # extend ActiveStorage::Associations::ActiveRecordExtensions
  has_one_attached :image

  belongs_to :category

end

  

app/models/purchase.rb
class Purchase < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one :purchase
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cooks_controller.rb
class CooksController < ApplicationController
  before_action :search_product, only: [:index, :search]

  def index
    @cooks = Cook.all
  end

  def new
    @cook = Cook.new
  end

  def create
    @cook = Cook.new(cooks_params)
    if @cook.save
      redirect_to root_path
    else
      render :new
    end
  end

  def search
    @results = @p.result.includes(:category)
  end

  private

  def cooks_params
    params.require(:cook).permit(:image, :title, :store, :cooksentence)
  end

  def search_cook
    @p = cook.ransack(params[:q])
  end
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  class MapsController < ApplicationController
    def index
        @maps = Map.all
        @map = Map.new
    end

    def create
        map = Map.new(map_params)
        if map.save
            redirect_to :action => "index"
        else
            redirect_to :action => "index"
        end
    end

    def destroy
        map = Map.find(params[:id])
        map.destroy
        redirect_to action: :index
    end

    private
    def map_params
    params.require(:map).permit(:address, :latitude, :longitude)
    end
end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :search_place, only: [:index, :search]

  def index
    @places = Place.all
  end

  def new
    @cook = Cook.new
  end

  def create
    @cook = Cook.new(cooks_params)
    if @cook.save
      redirect_to root_path
    else
      render :new
    end
  end

  def search
    @results = @p.result.includes(:category)
    @places = Place.all
    @cooks = Cook.all
  end

  private

  def search_place
    @p = Place.ransack(params[:q])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cook_helper.rb
module CookHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/cooks/_cook.html.erb
<div class="card">
  <%= link_to image_tag(cook.image), prototype_path(cook.id), class: :card__img  %>
  <div class="card__body">
    <%= link_to cook.title,cook_path(cook.id),class: :card__title %>
    <p class="card__summary">
      <%= cook.store %>
    </p>
    <%# <%= link_to "by#{prototype.user.name}", user_path(prototype.user.id), class: :card__user %> %>
  </div>
</div>

 

app/views/cooks/_form.html.erb
<%= form_with model: cook, local: true do |f|%>

  <div class="field">
    <%= f.label :image,"画像"%><br />
  
<% end %>

app/views/cooks/edit.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">プロトタイプ編集</h2>
      <%# 部分テンプレートでフォームを表示する %>
       <%= render partial: "form",locals: { prototype: @prototype } %>
    </div>
  </div>
</div>
<

app/views/cooks/index.html.erb
<main class="main">
  <div class="inner">
    <%# ログインしているときは以下を表示する %>
    <% if user_signed_in? %>
      <div class="greeting">
        こんにちは、
        <%# <%= link_to "#{current_user}さん", user_path(current_user), class: :greeting__link%> %>
         </div> 
      <% end %>  

    <%# // ログインしているときは上記を表示する %>
    
    <%# <div class="card__wrapper">
  <%= render partial: 'cook', collection: @cooks %>
<%# </div> %> 
    </div>
  </div>
</main>



 

app/views/cooks/new.html.erb
        <%= render partial: "form",locals: { cook: @cook } %>
    </div>
  </div>
</div>


 <%= form_with model:@cook,local: true do |f| %>
 <%= f.file_field :image, id:"cook-image" %>
  <div class="new-items">
      <div class="weight-bold-text">
        商品名
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :title, class:"items-text", id:"phileo-name", placeholder:"商品名（必須 40文字まで)", maxlength:"40" %>
      <div class="items-explain">
        <div class="weight-bold-text">
          商品の説明
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :store, class:"items-text", id:"item-info", placeholder:"商品の説明（必須 1,000文字まで）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。" ,rows:"7" ,maxlength:"1000" %>
      </div>
      </div>
        <%= f.text_area :cooksentence, class:"items-text", id:"item-info", placeholder:"商品の説明（必須 1,000文字まで）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。" ,rows:"7" ,maxlength:"1000" %>
    </div>
   <%= f.submit "登録する" ,class:"sell-btn" %>
     <% end %>

app/views/cooks/show.html.erb
<main class="main">
  <div class="inner">
    <div class="prototype__wrapper">
      <p class="prototype__hedding">
        <%= @prototype.title%>
      </p>
      <%= link_to "by #{@prototype.user.name}", user_path(@prototype.user.id), class: :prototype__user %>
      <%# プロトタイプの投稿者とログインしているユーザーが同じであれば以下を表示する %>
        <div class="prototype__manage">
        <% if user_signed_in? && current_user.id == @prototype.user_id %>
          <%= link_to "編集する", edit_prototype_path(@prototype.id), class: :prototype__btn %>
          <%= link_to "削除する", prototype_path(@prototype.id), method: :delete, class: :prototype__btn %>
        <% end %>   
        <%# #どの投稿を削除するのかIDを渡してあげrルカどうか %>
        </div>
      <%# // プロトタイプの投稿者とログインしているユーザーが同じであれば上記を表示する %>
      <div class="prototype__image">
        <%= image_tag(@prototype.image) %>
      </div>
      <div class="prototype__body">
        <div class="prototype__detail">
          <p class="detail__title">キャッチコピー</p>
          <p class="detail__message">
            <%= @prototype.catch_copy %>
          </p>
        </div>
        <div class="prototype__detail">
          <p class="detail__title">コンセプト</p>
          <p class="detail__message">
            <%= @prototype.concept %>
          </p>
        </div>
      </div>
      <div class="prototype__comments">
        <%# ログインしているユーザーには以下のコメント投稿フォームを表示する %>
         <%if user_signed_in?%>
          <%= form_with model: [@prototype,@comment],local: true do |f| %>
            <div class="field">
              <%= f.label :comment, "コメント"%>
              <%= f.text_field :text, placeholder: "comment_text" %>   
            </div>
            <div class="actions">
              <%= f.submit "送信する", class: :form__btn %>
            </div>
          <% end %>
          <%end%>
        <%# // ログインしているユーザーには上記を表示する %>
        <ul class="comments_lists">
          <%# 投稿に紐づくコメントを一覧する処理を記述する %>
            <li class="comments_list">
              <%= " コメントのテキスト "%>
              <% @comments.each do |comment| %>
        <p>
          
          <%= comment.text %>
        </p>
          <%= link_to comment.user.name, user_path(comment.user.id), class: :comment_user %>
      <% end %>
             
            </li>
          <%# // 投稿に紐づくコメントを一覧する処理を記述する %>
        </ul>
      </div>
    </div>
  </div>
</main>

app/views/layouts/_prototype.html.erb
<div class="card">
  <%= link_to image_tag("プロトタイプの画像", class: :card__img ), root_path%>
  <div class="card__body">
    <%= link_to "プロトタイプのタイトル", root_path, class: :card__title%>
    <p class="card__summary">
      <%= "プロトタイプのキャッチコピー" %>
    </p>
    <%= link_to "by プロトタイプの投稿者名", root_path, class: :card__user %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>PHILEO</title>

    <title></title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP:400,700,900&display=swap" rel="stylesheet">
  </head>

  <body>
  
    <header class="header">
      <div class="inner">
        <div class="nav">
          <div class="nav__left">
           
          </div>
          <% if user_signed_in? %>
            <div class="nav__right">

              <%# <%= link_to "ログアウト",  destroy_user_session_path, method: :delete, class: :nav__btn  %> 

              <%= link_to "ログアウト",  destroy_user_session_path, method: :delete, class: :nav__btn  %>

              <%# <%= link_to "New Proto",  new_prototype_path, class: :nav__btn %> 
            </div> 
          <%# // ログインしているときは上記を表示するようにしましょう %>
          <%# ログインしていないときは以下を表示するようにしましょう %>
           <% else %>
            <div class="nav__right">
              <%# <%= link_to "ログイン", new_user_session_path, class: :nav__btn %>

              <%# <%= link_to "新規登録",  new_user_registration_path, class: :nav__btn %>

              <%# <%= link_to "新規登録",  new_user_registration_path, class: :nav__btn %> 

            </div>
            <% end %>
          <%# // ログインしていないときは上記を表示するようにしましょう %>
        </div>
      </div>
    
    </header>
    <%= yield %>
    <%# <footer class="footer">
      <p class="copyright">Copyright © PROTO SPACE All rights reserved.</p>
    </footer>
  </body>
</html> %>

app/views/layouts/pplication.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>ProtoSpace</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP:400,700,900&display=swap" rel="stylesheet">
  </head>

  <body>
    <header class="header">
    <% if user_signed_in? %>
        <div class="user_nav grid-6">
          <span><%= current_user.name %>
            <ul class="user__info">
              <li>
                <%= link_to "マイページ", "/users/#{current_user.id}" %>
                <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
              </li>
            </ul>
          </span>
          <%= link_to "投稿する", new_tweet_path, class: "post" %>
        </div>
      <% else %>
      <div class="inner">
        <div class="nav">
          <div class="nav__left">
            <%= link_to image_tag("logo.png", class: :logo), root_path %>
          </div>
            <div class="nav__right">
              <%= link_to "ログイン", root_path, class: :nav__btn %>
              <%= link_to "新規登録", root_path, class: :nav__btn %>
            </div>
          <%# // ログインしていないときは上記を表示するようにしましょう %>
        </div>
      </div>
    </header>
     <% end %>
    <%= yield %>
    <footer class="footer">
      <p class="copyright">Copyright © PROTO SPACE All rights reserved.</p>
    </footer>
  </body>
</html>

app/views/places/index.html.erb
<!DOCTYPE HTML>
<html>
<head>
  <meta charset="UTF-8">
  PHILEO
  <p>
    ”絶対にハズさない美味しいお店を検索できる'
  </p>
</head>
<h1>

</h1>

<style>
  #top-search {
    width: 100%;
    height: 480px;
    margin-bottom: 100px;
    background: url('https://imgsv.nikon-image.com/products/mirrorless/lineup/z_50/img/sample/pic_01_l.jpg') no-repeat 50%;
    background-size: cover;
  }
</style>

<div id="top-search">
  <%= search_form_for @p, url: places_search_path do |f| %>
    <%= f.label :place_name_eq, '沖縄県' %>
    <%= f.collection_select :name_eq, @places, :name, :name, include_blank: '指定なし' %>
    <br>
    <%= f.submit '検 索' %>
  <% end %>

  <%= form_with url: new_cook_path, local: true do |f| %>
    <%= f.submit "DBの登録", class: "sel-btn" %>

  <% end %>
</div>

<%# 商品一覧 %>
<% @places.each do |place| %>
  <br>
  <li>
    <%= place.name %>

  </li>
<% end %>

app/views/places/new.html.erb
<%= form_with model:@cook,local: true do |f| %>
 <%= f.file_field :image, id:"cook-image" %>
   <%= f.submit "登録する" ,class:"sell-btn" %>
     <%= image_tag(url_for(@cook.avatar)) %>
     
 <% end %>
<%= form_with model:map,local: ture do |f|%>
<%= f.file_field :maps, id:"maps-gogole" %>
   <%= f.submit "登録する" ,class:"sel-btn" %>
   
 <% end %>

app/views/places/search.html.erb
<div class="side-bar">
</div>
<script src="http://maps.google.com/maps/api/js?key=AIzaSyAc8ucfbF9aY5Jn9VehhJZ852fopENuQTc"></script>
<style>
  html {
    height: 100%
  }
  body {
    height: 50%
  }
  #map {
    height: 50%;
    width: 50%
  }
</style>
<body>
<div class='phileo-info'>
  <h1>
    PHILEOグルメ '絶対にハズさない 美味しいお店を検索できる'
  </h1>
</div>

<style>
  .wrapper {
    display: flex;
  }
  .side-bar {
    width: 200px;
    padding: 20px;
    background: #f5f5f5;
    border-radius: 10px;
  }
  /*テンポ一覧*/
  .cooks {
    width: 100%;
  }
  .item {
    display: flex;
  }
  .item-img {
    width: 200px;
    overflow: visible;
  }
  img {
    width: 100%;
  }
  .item-price {
    width: 100%;
    height: auto;
    margin-right: 30px;
  }
  .item-store {
    font-size: 14px;
  }
  #map {
    height: 350px;
    width: 100%;
  }
  .avatar {
    width: 50px;
    height: 50px;
  }
  .avatar img {
    border-radius: 50%;
    border: 1px solid #ccc;
  }
</style>

<div class="wrapper">
  <div class="side-bar">
    <ul>
      <li>hogehoge</li>
      <li>hogehoge</li>
      <li>hogehoge</li>
      <li>hogehoge</li>
      <li>hogehoge</li>
      <li>hogehoge</li>
      <li>hogehoge</li>
    </ul>
  </div>
  <div class="cooks">
    <div id="map"></div>
    <% @cooks.each do |cook| %>
      <div class='item'>
        <div class='item-img'>
          <img src="https://tandems.co.jp/images/member_osaka.png" alt="">
        </div>
        <div class='item-price'>
          <div class="avatar">
            <img src="https://tandems.co.jp/images/member_osaka.png" alt="">
          </div>
          <h3 class='item-name'>
            <%= cook.title %>
          </h3>
          <div class='item-store'>
            <%= cook.store %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

<div class='item-info'>
  <script>
    const cooks = <%== Cook.all.to_json %>;
    console.log(cooks);

    var MyLatLng = new google.maps.LatLng(26.2125, 127.68111);
    var Options = {
      icon: { url: 'https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixta.jp%2Fillustration%2F12767983&psig=AOvVaw0JcQTIocWdS2K6xFdU8EYV&ust=1638779689532000&source=images&cd=vfe&ved=0CAsQjRxqFwoTCJjvx5ygzPQCFQAAAAAdAAAAABAO' },
      zoom: 15,      //地図の縮尺値
      center: MyLatLng,    //地図の中心座標
      mapTypeId: 'roadmap'   //地図の種類
    };
    var map = new google.maps.Map(document.getElementById('map'), Options);
    var marker = new google.maps.Marker({
      map: map,
      position: { lat: 26.2125, lng: 127.68111 },
    });
    var MyLatLng = new google.maps.LatLng(26.2123, 127.68113);
    var Options = {
      zoom: 15,      //地図の縮尺値
      center: MyLatLng,    //地図の中心座標
      mapTypeId: 'roadmap'   //地図の種類
    };
    var map = new google.maps.Map(document.getElementById('map'), Options);
    var marker = new google.maps.Marker({
      map: map,
      position: { lat: 26.214803, lng: 127.676176 },
    });

    var marker = new google.maps.Marker({
      map: map,
      position: { lat: 26.2155658, lng: 127.6691134 },
    });
    var marker = new google.maps.Marker({
      map: map,
      position: { lat: 26.214098, lng: 127.677487 },
    });

    infoWindow = new google.maps.InfoWindow({ // 吹き出しの追加
      content: '<div class="mapSample">泡盛倉庫</div>' +
        '<img src="https://tandems.co.jp/images/member_osaka.png" alt="" width="40">'
    });
    marker.addListener('click', function() { // マーカーをクリックしたとき
      infoWindow.open(map, marker); // 吹き出しの表示    
    });
  </script>
</body>

<h1>
  検索結果
</h1>

<% @places.each do |place| %>
  <br>
  <li>
    <%= place.name %>

  </li>
<% end %>

該当する商品はありません

<%= link_to 'トップページへ戻る', root_path %>

app/views/places/search2.html.erb
<h1>
  検索結果
</h1>
<%# 検索結果の個数で条件分岐 %>

  <% @results.each do |result| %>
    <br>
    <li>
      <%= result.name %>
      <%= result.size %>
      <%= result.status %>
      <%= result.price %>
      <%= result.category.name %>
    </li>
  <% end %>
<% else %>
  該当する商品はありません
<% end %>
<%= link_to 'トップページへ戻る', root_path %>